// extension/src/popup-react/pages/AutomationPage.tsx
import type { PopupControllerState } from "../../popup-shared/popup-controller.js";
import { FeatureActionsCard } from "../components/FeatureActionsCard.js";
import { UnsupportedPageView } from "./UnsupportedPageView.js";

type AutomationPageProps = Pick<
  PopupControllerState,
  "state" | "viewModel" | "larkActions" | "meegleActions"
> & {
  onFeature: (key: string) => void | Promise<void>;
};

export function AutomationPage({
  state,
  viewModel,
  larkActions,
  meegleActions,
  onFeature,
}: AutomationPageProps) {
  return (
    <div className="automation-page" data-test="automation-page">
      {viewModel.showUnsupported ? <UnsupportedPageView /> : null}
      {!viewModel.showUnsupported && state.pageType === "lark" ? (
        <FeatureActionsCard title="Lark 功能" actions={larkActions} onAction={onFeature} />
      ) : null}
      {!viewModel.showUnsupported && state.pageType === "meegle" ? (
        <FeatureActionsCard
          title="Meegle 功能"
          actions={meegleActions}
          onAction={onFeature}
        />
      ) : null}
    </div>
  );
}

// extension/src/popup/pages/AutomationPage.vue
<template>
  <div class="automation-page" data-test="automation-page">
    <UnsupportedPageView
      v-if="viewModel.showUnsupported"
      data-test="unsupported-view"
    />
    <template v-else-if="state.pageType === 'lark'">
      <FeatureActionsCard
        title="Lark 功能"
        :actions="larkActions"
        @action="$emit('feature', $event)"
      />
    </template>
    <template v-else-if="state.pageType === 'meegle'">
      <FeatureActionsCard
        title="Meegle 功能"
        :actions="meegleActions"
        @action="$emit('feature', $event)"
      />
    </template>
  </div>
</template>

<script setup lang="ts">
import type { PopupFeatureAction } from "../types.js";
import type { PopupViewModel } from "../view-model.js";
import FeatureActionsCard from "../components/FeatureActionsCard.vue";
import UnsupportedPageView from "./UnsupportedPageView.vue";

defineProps<{
  state: { pageType: string };
  viewModel: PopupViewModel;
  larkActions: PopupFeatureAction[];
  meegleActions: PopupFeatureAction[];
}>();

defineEmits<{
  feature: [key: string];
}>();
</script>

<style scoped>
.automation-page {
  display: grid;
  gap: 12px;
}
</style>
