// extension/src/popup-react/pages/UnsupportedPageView.tsx
import { UiCard } from "../components/UiCard.js";

export function UnsupportedPageView() {
  return (
    <UiCard>
      <div className="unsupported-view" data-test="unsupported-view">
        <div className="unsupported-icon">!</div>
        <div className="unsupported-copy">
          <p className="unsupported-title">当前页面不支持</p>
          <p className="unsupported-hint">请在 Lark 或 Meegle 页面使用</p>
        </div>
      </div>
    </UiCard>
  );
}

// extension/src/popup/pages/UnsupportedPageView.vue
<template>
  <a-card size="small">
    <a-empty description="当前页面不支持">
      <template #image>
        <div class="unsupported-icon">🚫</div>
      </template>
      <p class="unsupported-hint">请在 Lark 或 Meegle 页面使用</p>
    </a-empty>
  </a-card>
</template>

<style scoped>
.unsupported-icon {
  font-size: 40px;
}

.unsupported-hint {
  margin: 0;
  color: #64748b;
  font-size: 12px;
}
</style>
