// extension/src/popup/components/FeatureActionsCard.vue
<template>
  <UiCard :title="title">
    <div class="feature-actions">
      <UiButton
        v-for="action in actions"
        :key="action.key"
        :variant="action.type === 'primary' ? 'primary' : 'default'"
        block
        :disabled="action.disabled"
        @click="$emit('action', action.key)"
      >
        {{ action.label }}
      </UiButton>
    </div>
  </UiCard>
</template>

<script setup lang="ts">
import type { PopupFeatureAction } from "../types.js";
import UiButton from "./UiButton.vue";
import UiCard from "./UiCard.vue";

defineProps<{
  title: string;
  actions: PopupFeatureAction[];
}>();

defineEmits<{
  action: [key: string];
}>();
</script>

<style scoped>
.feature-actions {
  display: grid;
  gap: 8px;
}
</style>

// extension/src/popup-react/components/FeatureActionsCard.tsx
import type { PopupFeatureAction } from "../../popup/types.js";
import { UiButton } from "./UiButton.js";
import { UiCard } from "./UiCard.js";

export function FeatureActionsCard({
  title,
  actions,
  onAction,
}: {
  title: string;
  actions: PopupFeatureAction[];
  onAction: (key: string) => void;
}) {
  return (
    <UiCard title={title}>
      <div className="feature-actions">
        {actions.map((action) => (
          <UiButton
            key={action.key}
            variant={action.type === "primary" ? "primary" : "default"}
            block
            disabled={action.disabled}
            onClick={() => onAction(action.key)}
          >
            {action.label}
          </UiButton>
        ))}
      </div>
    </UiCard>
  );
}
