// extension/src/popup/components/PopupPage.vue
<template>
  <section class="popup-page" data-test="popup-page">
    <header v-if="title || subtitle" class="popup-page__header">
      <div class="popup-page__copy">
        <h2 v-if="title" class="popup-page__title">{{ title }}</h2>
        <p v-if="subtitle" class="popup-page__subtitle">{{ subtitle }}</p>
      </div>
      <div v-if="$slots.actions" class="popup-page__actions">
        <slot name="actions" />
      </div>
    </header>

    <div class="popup-page__body">
      <slot />
    </div>

    <footer v-if="$slots.footer" class="popup-page__footer">
      <slot name="footer" />
    </footer>
  </section>
</template>

<script setup lang="ts">
defineProps<{
  title?: string;
  subtitle?: string;
}>();
</script>

<style scoped>
.popup-page {
  display: grid;
  gap: 16px;
}

.popup-page__header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 12px;
}

.popup-page__copy {
  min-width: 0;
}

.popup-page__title {
  margin: 0;
  font-size: 18px;
  line-height: 1.15;
  color: #0f172a;
}

.popup-page__subtitle {
  margin: 6px 0 0;
  font-size: 13px;
  line-height: 1.5;
  color: #64748b;
}

.popup-page__body {
  display: grid;
  gap: 12px;
}

.popup-page__footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
}
</style>

// extension/src/popup-react/components/PopupPage.tsx
import type { PropsWithChildren, ReactNode } from "react";

export function PopupPage({
  title,
  subtitle,
  actions,
  footer,
  children,
}: PropsWithChildren<{
  title?: string;
  subtitle?: string;
  actions?: ReactNode;
  footer?: ReactNode;
}>) {
  return (
    <section className="popup-page" data-test="popup-page">
      {(title || subtitle) && (
        <header className="popup-page__header">
          <div className="popup-page__copy">
            {title ? <h2 className="popup-page__title">{title}</h2> : null}
            {subtitle ? <p className="popup-page__subtitle">{subtitle}</p> : null}
          </div>
          {actions ? <div className="popup-page__actions">{actions}</div> : null}
        </header>
      )}
      <div className="popup-page__body">{children}</div>
      {footer ? <footer className="popup-page__footer">{footer}</footer> : null}
    </section>
  );
}
